### ISSUE TITLE
pg-pool swallows errors

### ISSUE THREAD

**Issue by cressie176** [brianc/node-pg-pool#24]
I'm seeing strange behaviour when using pg-pool. The following script demonstrates the problem

``` js
const Pool = require('pg-pool')
const pool = new Pool()

pool.connect((err, client, close) => {
  client.query('SELECT 1', () => {
    close()
    pool.connect((err, client, close) => {
      throw new Error()
    })
  })
})

setInterval(() => {}, Number.MAX_VALUE)
```

Instead of crashing, the error is swallowed. I noticed this because my code was programatically building a query, and thew an error because of an undefined variable. e.g.

``` js
const Pool = require('pg-pool')
const pool = new Pool()

pool.connect((err, client, close) => {
  client.query('SELECT 1', () => {
    close()
    pool.connect((err, client, close) => {
      const statement = getStatment() // Typo meant getStatment was not defined
      client.query(statement, (err, result) => {
        console.log(result)
      })
    })
  })
})
```

**Comment by cressie176** [comment]
Is this project still maintained?

**Comment by brianc** [comment]
Yes.

**Comment by iamchenxin** [comment]
@cressie176 Its not a bug. its promise's default behavior.(Promise will do no thing, when you did not catch  a reject).
You could listen the event [`unhandledrejection`](https://nodejs.org/api/process.html#process_event_unhandledrejection) to change the default behavior.
```
process.on('unhandledRejection', (reason, promise) => {
  console.log('Unhandled Rejection at: Promise', promise, 'reason:', reason);
  // application specific logging, throwing an error, or other logic here
});
```
`unhandledrejection` will listen all unhandled rejection of promise.(So you can throw in inner without catch them).

**Comment by cressie176** [comment]
Hi @iamchenxin. Thanks for the response. I'm using the callback API so not able to catch a reject. Also listening process.on('unhandledRejection') isn't going to help much since that could be caused by any unhandled rejection, not specifically one raised by the pg internals.

I'd definitely argue that this is a bug with pg (or one of its libs) since users of the callback API shouldn't need to understand the libraries internals. By convention any errors should be passed the callback via the err argument.

**Comment by iamchenxin** [comment]
@cressie176 look it again, seems this is not only belong to `node-postgres/query.js`. all functions which using Promise inner keep the Promise's default behavior too.(ex:  `pool.connect` ). (Test with nodejs 6.31, but im not sure to this, a little sleepy)
Maybe you could pass a bluebird Promise to the pool's config, so the global Promise will keep the origin behavior (The bluebird's default behavior will raise a error when not catch a reject). 

Or You could temporaryily chain a catch below your original function. 
```
    pool.connect((err, client, close) => {
      throw new Error()
    }).catch( e => { // catch it here...

    })
```

 I think may be the callback's behavior should be separated from promise too.

**Comment by cressie176** [comment]
Thanks again @iamchenxin. Both those options (bluebird and catch) work with my simplified example, but unfortunately aren't viable options with the real code.

The problem is that the Bluebird intercepts unhandled rejection and logs it, but there's still no way (I've been able to find) to do anything intelligent with the error.

catching the error after each call does appear to work, but doing that renders the callback API worse than pointless for two reasons 

1. The catch is likely to intercept any error thrown by end user code, and not just database related ones
2. The likely response to both a callback err and caught err will be to return cb(err). It's possible in this circumstance to execute cb(err) twice, causing all sorts of problems with any code that uses async.

**Comment by iamchenxin** [comment]
@cressie176 
This is how pg-pool works, currently callback is wrapped in Promise(so the Exception throwed in callback will be handled by Promise).  If you need a raw callback's behavior, you must rewrite this code, (build a callback layer, and a Promise layer above it.). Seems there is no simply way to produce the raw callback's behavior, except rewrite this.
```
Pool.prototype.connect = function (cb) {
  return new this.Promise(function (resolve, reject) {
    this.log('acquire client begin')
    this.pool.acquire(function (err, client) {
      if (err) {
        this.log('acquire client. error:', err)
        if (cb) {
          cb(err, null, function () {})
        }
        return reject(err)
      }

      ........

      if (cb) {
        cb(null, client, client.release)
      }

      return resolve(client)
    }.bind(this))
  }.bind(this))
}
```

**Comment by cressie176** [comment]
Thanks for your time and explanation @iamchenxin . Unless @brianc has any good suggestions I don't think I'll just have to live with the unhandledRejection approach.

**Comment by brianc** [comment]
@cressie176 sorry I've been a bit AWOL - I get busy & things fall by the wayside.  I definitely want to fix this - having errors disappear without warning is a pretty big problem.  I'll move it to the top of my queue and get to it soon. I really appreciate the example you submitted as a clear case for how to reproduce the issue.  I'll ping you when I put the pull request.  

@iamchenxin thanks for the investigation you did!  It may indeed require a bit of rewriting - I'd like to end up at a place where the functionality can be maintained.  If there is no way to do it in a backwards compatible way it may take a bit longer. In the next major version of pg we want to ship node-postgres core without promises, pg-pool without promises, and ship `*-as-promised` versions or an additionaly thing to require in which can allow people to seamlessly "opt-in" to promises.  I think that's how we might want to go anyway - still discussing it with @joskuijpers and have been super busy with travel & family stuff so haven't had a lot of time.  Feedback is always welcome!

**Comment by cressie176** [comment]
Thanks @brianc, that's perfect. I like the idea of shipping a promise free postgres-core, with an optional as promised wrapper. No need to apologise for being AWOL, I really appreciate the effort you and the other contributors have put in node-postgres.

**Comment by shakaIsReal** [comment]
+1 here's my situation `
pool.query(`select * from userz`, function(err, reply) {
// ...
})
` 
with this code i still get `Possibly Unhandled Rejection at: ...` But changing it to `client.query()` works. The only way to make `pool` work is to use `catch(err => ... )`
