### ISSUE TITLE
What is the proper way to use transactions with async/await promises?

### ISSUE THREAD

**Issue by rightaway** [brianc/node-pg-pool#27]
I'd like to use pg-pool to work with transactions, where I run a BEGIN followed by a few SQL statements then a COMMIT/ROLLBACK. But I'd like to do this with async/await, taking advantage of pg-pool's use of promises. Could you please provide any examples of the proper way to do this with pg-pool?

**Comment by vitaly-t** [comment]
You can get good answers by publishing your question on StackOverflow, because the author here has objections to publishing here references to modules that solve it, that's why I won't put here any.

**Comment by brianc** [comment]
@rightaway this is how I do it:


```js
const client = await pool.connect()
try {
  await client.query('BEGIN')
  const { rows } = await client.query('INSERT INTO users (name) values ($1) returning *', ['brianc'])
  const user = rows[0]
  const result = await client.query('INSERT INTO user_sessions (user_id, session_id) VALUES ($1, $2) returning *', [user.id, 1])
  await client.query('COMMIT')
  return result.rows[0].session_id
} catch (e) {
  client.query('ROLLBACK')
} finally {
  client.release()
}
```

The queries there are a bit arbitrary but I hope that conveys the idea pretty clearly? :smile:

**Comment by vitaly-t** [comment]
what happened to my answer? :)

**Comment by rightaway** [comment]
@brianc Do the last few lines `client.release()` and `client.query('ROLLBACK')` also need an await before it?

@vitaly-t Was the way you do it similar to what was posted or were you going to suggest a different way?

**Comment by vitaly-t** [comment]
@rightaway my answers get deleted here, such a waste of time... you should ask your questions somewhere else.

**Comment by brianc** [comment]
Hopefully this is helpful:

https://node-postgres.com/features/transactions

**Comment by rightaway** [comment]
https://node-postgres.com/features/transactions has `client.release()` near the bottom, should it be `await client.release()` or is it fine without the `await`?

**Comment by charmander** [comment]
@rightaway It’s fine without the `await`. `client.release()` without an error doesn’t perform any I/O (yet), but even if it did, you wouldn’t have to wait for it to complete, and any errors would be emitted by the pool.

**Comment by rightaway** [comment]
@charmander If errors would be emitted by the pool in that case I'd specifically have to subscribe to those error events somehow?

**Comment by charmander** [comment]
@rightaway Yes; see [the pool error listener in the pg README][1], for example.

[1]: https://github.com/brianc/node-postgres/tree/dbf3bd3304a41d759f5c5c0bf86a2f4b6ac8d7db#pooling-example
