### ISSUE TITLE
Upgrade to generic-pool v3

### ISSUE THREAD

**Issue by sandfox** [brianc/node-pg-pool#29]
It's still not quite finished, but the API changes are all done and pending any critical bugs should be final. 
The 2 big changes are 
- the move over to using promises instead of callbacks (except for the "pooled" function which I still haven't quite worked out yet)
- nodejs v4+ support only. It uses various ES6 stuff which is only available in node4.

Minor changes include renaming/removing some config options and constructor args.

Before I get started on the PR for this, I just wanted to check that your ok with doing this.

EDIT --
Also - totally up for any suggestions of things you'd like to see in it or questions about the changes or anything you think is completely daft, or if you'd like me to explain anything!

**Comment by brianc** [comment]
Most definitely!

**Comment by abenhamdine** [comment]
Is the v3 to support acquire time out ?
If I'm correct, this feature is needed to allow to have an error in case of time out with pg.connect.

**Comment by sandfox** [comment]
@abenhamdine yep, the acquire call timeout support (and ability to more easily add timeouts for other operations) is in the v3 branch. It also isolates factory errors from acquire calls so the two are no longer linked/locked 1:1.

**Comment by abenhamdine** [comment]
ah fabulous, can't wait 💃 😄

**Comment by sandfox** [comment]
ok, finally published the new version after some serious detours. (and already have bugs to deal with!)
@brianc - whats the baseline version of nodejs pg-pool is designed to work with?  At the moment, generic-pool v3 requires node v4 because it uses Promises, Sets, Maps and some other es6-isms. With some work it's probably possible to make some version of generic pool (or a module that wraps it) that could shim out those requirements with some < node 4 compatible equivalents.

Thoughts?

**Comment by brianc** [comment]
Generic pool has been removed as a dependency. in `pg-pool@2.0`
