### ISSUE TITLE
1.6.0 broke backward compatibility by returning undefined on connect()

### ISSUE THREAD

**Issue by diegoperini** [brianc/node-pg-pool#38]

**Comment by charmander** [comment]
Yes, I mentioned that it would, but it was published as a minor version anyway – maybe because it wasn’t intentional to begin with. Anyway, use 1.4.x (not 1.5.x) if you need to for some reason.

**Comment by brianc** [comment]
My apologies for that.  Out of curiosity, what did it return before?

**Comment by charmander** [comment]
A promise, even when a callback was provided, causing #24. Since the behaviour wasn’t documented and there was never a use case for it, though, this isn’t really a problem.

**Comment by brianc** [comment]
Ohh okay cool - well this is fixed in 2.0! :dancer:

**Comment by brianc** [comment]
My appologies for breaking backwards compat - I'll try to keep an eye out for that in the future.
