### ISSUE TITLE
Notification event does not work

### ISSUE THREAD

**Issue by Globik** [brianc/node-pg-pool#40]
No event works with perform pg_notify.

**Comment by rightaway** [comment]
`pool.on('notification', callback)` doesn't work for you?

**Comment by Globik** [comment]
I don't know. But I'll try. I'm using node-pg-pool version 1.6.0 and node-pg-subpub

**Comment by rightaway** [comment]
Try getting the `client` from the `pool`, it works for me. Here's an ES6 example.

```js
  const client = await pool.connect()
  client.on('notification', msg => {
    console.log(msg)
  })
  client.query('LISTEN channel')
```

**Comment by brianc** [comment]
I would recommend strongly against using a pooled client for `listen/notify`.  For the listener instantiate a stand-alone client and connect it.  The pool will close clients which haven't been checked out after a configurable interval - including any clients which you have have called `listen` on.

I have it on my roadmap to document proper usage of `listen/notify` - for now just don't use the pool for that client:

```
const listener = new pg.Client()
listener.connect()
listener.query('LISTEN channel')
listener.on('notification', msg => {
  // do your thing here
})
```
