### ISSUE TITLE
connection string for pg-native

### ISSUE THREAD

**Issue by nonword** [brianc/node-pg-pool#41]
I'm trying to use this with pg-native and finding that clients aren't connecting to the connection properties I'm passing in. They instead fall back on environmental variables. 

I can [see that pg-pool passes the connection hash to the Client constructor, but passes nothing but a `cb` to the connect method](https://github.com/brianc/node-pg-pool/blob/master/index.js#L57-L78). Pg-native [expects connection config in the latter](https://github.com/brianc/node-pg-native/blob/master/index.js#L38-L40). Furthermore, it expects it as a string, following the [libpq convention](https://www.postgresql.org/docs/9.3/static/libpq-connect.html). 

Should I pass in a [custom create handler](https://github.com/brianc/node-pg-pool/blob/master/index.js#L17) so that I control how (pg-native) clients are created? Or is there a better solution?

My test script:
```const url = require('url')
const Pool = require('pg-pool')

const config = require('config')

// pg.url has form: "postgresql://user@localhost:5432/dbname",
const params = url.parse(config.get('pg.url'))
const auth = params.auth.split(':')

const connectionConfig = { 
  user: auth[0],
  password: auth[1],
  host: params.hostname,
  port: params.port,
  database: params.pathname.split('/')[1],
  ssl: true,
  Client: require('pg-native'),
  min: 4,
  max: 40, 
  idleTimeoutMillis: 1000
}
console.log('Connecting with: ', connectionConfig)
const pool = new Pool(connectionConfig)

pool.connect().then((client) => {
  client.query('select $1::text as name', ['pg-pool']).then((res) => {
    client.release()
    console.log('hello from', res.rows[0].name)
  })  
  .catch((e) => {
    client.release()
    console.error('query error', e.message, e.stack)
  })  
}).catch((e) => {
  console.error('error connecting: ', e.message, e.stack)
})
```

Note: Commenting out `  Client: require('pg-native'),` causes it to succeed.

**Comment by jfsimon** [comment]
I succeeded using pooling and `pg-native` this way:

```js
import pg from 'pg';

const pool = new pg.Pool({
    user: 'user',
    password: 'pass',
    host: 'localhost',
    port: 5432,
    database: 'database',
    Client: pg.native.Client
});
```

**Comment by jgeurts** [comment]
Could you connect with the following?

```
const Pool = require('pg-pool');
const config = require('config')

const pool = new Pool({
  connectionString: config.get('pg.url')
});
```

**Comment by nonword** [comment]
I can't reproduce on latest versions of pg-native/pg-pool - nor using versions contemporaneous with the original issue - so I'm going to close this. Sorry for the noise. Thanks!
