### ISSUE TITLE
How to make a synchronous query?

### ISSUE THREAD

**Issue by haalgamu** [brianc/node-pg-pool#44]
I am trying to create a method for a synchronous query. I'm using pg-pool and asyncawait, but I throw the following error: "Error: await functions, yield functions, and value-returning suspendable functions may only be called from within a suspendable function."

The code is:

```
CustomPool = function(condigDB){
 this.pool = new Pool(cofigDB)
};

CustomPool.prototype.querySync = function(sql){
    var result = {rows:[]};
    try{
        result = await(this.pool.query(sql));
    }
    catch(_e_){
        Log.exception(_e_);
    }
    return result.rows; 
};

module.exports = CustomPool;
```

**Comment by charmander** [comment]
Synchronous queries aren’t supported. [Hacks](https://www.npmjs.com/package/deasync) exist, however.
