### ISSUE TITLE
pg dependency

### ISSUE THREAD

**Issue by spudly** [brianc/node-pg-pool#45]
`pg-pool` requires `pg` but does not include it in either `dependencies` or `peerDependencies`

**Comment by brianc** [comment]
Yah it doesn't require any specific version of `pg` so it's up to you to install whichever version of `pg` you'd like & then `pg-pool`.  I put that in the readme.  I have a lot of existing projects with different versions of `pg` installed and want both pg & pg-pool at the top level in npm.  I'm open to changing it but I prefer to install them each myself.

**Comment by charmander** [comment]
`{"peerDependencies": {"pg": "*"}}` might satisfy everyone, then?

**Comment by spudly** [comment]
@charmander, yes that's what it should be
