### ISSUE TITLE
Fails to reconnect after invoking end()

### ISSUE THREAD

**Issue by vitaly-t** [brianc/node-pg-pool#58]
We call `end()` on the pool in order to shut down all the connections within the pool.

However, doing so prevents us from being able to use the object any longer.

Any attempt of calling `.connect` after `.end()` was called once results in the following error:

```
pool is draining and cannot accept work
```

Below is a complete test application:

```js
'use strict';

var pg = require('pg');

var config = {
    database: 'newone',
    port: 5433,
    user: 'postgres'
};

var pool = new pg.Pool(config);

function test1() {
    pool.connect((err, client, done) => {
        if (err) {
            console.log('Error Connecting:', err);
            return;
        }
        client.query('select count(*) from users', (err, data) => {
            if (err) {
                console.log('Query Error:', err);
            } else {
                console.log('DATA:', data.rows);
            }
            done();
            pool.end();
            test2();
        });
    });
}

function test2() {
    pool.connect((err, client, done) => {
        if (err) {
            console.log('Error Connecting:', err);
            return;
        }
        client.query('select count(*) from users', (err, data) => {
            if (err) {
                console.log('Query Error:', err);
            } else {
                console.log('DATA:', data.rows);
            }
            done();
            pool.end();
        });
    });
}

test1();
```

`test1` ends successfully, but in `test2` it always throws that error on this line:

```js
console.log('Error Connecting:', err);
//=> pool is draining and cannot accept work
```

**Comment by brianc** [comment]
Yeah - once you call `end()` on the pool it's over: it's being disposed of.  You'll need to create a new pool.  That's behavior as designed.

**Comment by vitaly-t** [comment]
But why? What is the reason for that?

**Comment by brianc** [comment]
That's how generic pool works: https://github.com/coopernurse/node-pool#draining

**Comment by vitaly-t** [comment]
I don't think it matters how that pool works though.

You encapsulate that pool in your library, that means you can set it to `null` within the `end` function, and then create a new one within the `connect` function, if required.

This would make it consistent with how connections used to work, and still work via `pg.connect`, that we can call `.end()` and then call `connect` after that successfully.

**Comment by vitaly-t** [comment]
or....maybe it is for the better...? I'm still debating over the cons and pros of it...

**Comment by vitaly-t** [comment]
@brianc If we agree that this is ok for the pool to shut down itself permanently, then we definitely need a way to determine when this has happened.

When we share a `Pool` object we need to be able in some situations to ask - `Was this pool terminated`?

Something like this:

```js
if(pool.isTerminated) {
    // do what needs to be done
}
```

**Comment by charmander** [comment]
Why would you destroy the pool if you still wanted to use it?

**Comment by vitaly-t** [comment]
@charmander as per earlier example, a `Pool` object is exposed by the library, to be shared with other third-party libraries, in order to avoid creation of an additional pool.

A third-party library may incorrectly end the pool, thus breaking all the other modules that use it.

As I wrote earlier, it is probably wise to keep it she `Pool` object destroyed, but we at least need a way to determine that, so it can be diagnosed easily, something like `pool.isTerminated`, see the example above.

**Comment by charmander** [comment]
> but we at least need a way to determine that, so it can be diagnosed easily

Maybe the message saying the pool is draining?

**Comment by vitaly-t** [comment]
> Maybe the message saying the pool is draining

We don't need any message, just an indication/flag, so any library can provide its own message.

**Comment by vitaly-t** [comment]
I've just found out that we can verify it through the `generic-pool` library:

```js
var p = new pg.Pool(connection);
var isTerminated = p.pool._draining;
```

though I'm not sure if it is a very good one, to rely on an internal module for this.

**Comment by vitaly-t** [comment]
Added a PR: https://github.com/brianc/node-pg-pool/pull/59
