### ISSUE TITLE
Does idleTimeoutMillis = -1 keep connections open indefinently

### ISSUE THREAD

**Issue by joekiller** [brianc/node-pg-pool#64]
Does `idleTimeoutMillis = -1` keep connections open indefinitely or cause them to close immediately? Reading the ops of [node-poo]l[1] led me to believe the connection would just stay open but this doesn't seem to be the case.

[1]:https://github.com/coopernurse/node-pool#documentation

**Comment by joekiller** [comment]
Thank you @brianc

**Comment by brianc** [comment]
Totally! Meant to come respond back to this: you can set it to `0` to disable it now. :) `pg-pool@2.x` is compatible with node>=v4.x and pg>=5.x - hopefully it works for you!
