### ISSUE TITLE
Get number of active clients

### ISSUE THREAD

**Issue by chiluap** [brianc/node-pg-pool#69]
Hi there,

nice work with the pg-pool.

just a thought:

for getting the number of active clients you suggest keeping a counter on the connect callback.
I suggest counting the number of active clients via something like:

```javascript
showConnections() {  
        logger.notice('PgPool.openConnections: ', {rw: this.pool._clients.length});
        setTimeout(_.bind(this.showConnections, this), 30000); 
}
```

(b.t.w: I'am using the pool in an es2015 wrapper class. so don't mind the this.pool it is an instance of the pg-pool)

... just a thought.

keep up the good work

chiluap

**Comment by brianc** [comment]
You can actually use [`pool.totalCount`](https://node-postgres.com/api/pool#-code-pool-totalcount-int-code-) to get the number of connections in pg-pool@2.0.  Where do I suggest counting? I'd like to go update that documentation.

**Comment by vitaly-t** [comment]
It would be great to be able to monitor how connections are being used, with something like a notification callback:

```js
onConnectionCountChange(newCount) {
}
```

**Comment by brianc** [comment]
if you want to get a callback whenever a connection is created use the `pool.on('connect')` event. That + checking `pool.totalCount` should be all you need to monitor connection counts changing. 😄
