### ISSUE TITLE
Connection timeout with full connection pool overwrites callback queue

### ISSUE THREAD

**Issue by freitagbr** [brianc/node-pg-pool#85]
I think there's an issue with the logic for handling connection timeouts with a full connection pool.

https://github.com/brianc/node-pg-pool/blob/master/index.js#L164:
```js
// set connection timeout on checking out an existing client
const tid = setTimeout(() => {
    // remove the callback from pending waiters because
    // we're going to call it with a timeout error
    this._pendingQueue = this._pendingQueue.filter(cb => cb === response.callback)
    response.callback(new Error('timeout exceeded when trying to connect'))
}, this.options.connectionTimeoutMillis)
```
On line 164, the intent is to remove the `response.callback` from `this._pendingQueue`, because it's going to be handled right now. However, it seems like it actually removes every callback but `response.callback` from the queue. Is this right?

**Comment by brianc** [comment]
Hmm you might be on to something. Im not at my computer now but can look in
the morning. Is this causing any reproducible issues for you?

**Comment by freitagbr** [comment]
Yeah, I was noticing that every once in a while, all of my connections would start timing out. The timeout issue itself is likely an issue with the database. However, when one of the connections in the pool timed-out, the rest of the connections also timed-out. And once all of the connections in the pool timed-out, all of the connections became zombies, and could not reconnect to the database. My connection pool also had reached the max number of connections (20 in my case).

If I'm reading the code correctly, it seems like this might be the cause. I haven't tried fixing it yet, though. If I can find something that reliably fixes the issue, I will let you know.

**Comment by ksmith97** [comment]
Any update on merging this fix?

**Comment by poolik** [comment]
Looks like we're hitting this issue as well. @brianc what's holding back this bug fix release?

**Comment by abenhamdine** [comment]
Hello @brianc, could you release a new version please ?  
I hit again this issue and it's very annoying when you have a pool exhausted.

**Comment by edevil** [comment]
@abenhamdine Thanks for the heads-up. This is indeed worrying. :(

**Comment by fzaninotto** [comment]
I'm also interested in using this fix in production.

**Comment by chamini2** [comment]
thanks, me too

**Comment by brianc** [comment]
published pg-pool@2.0.4

**Comment by kamarajuPrathi** [comment]
We still see this error , Can you let us know whats the reason for the check , we are using pg node-postgres libarary which is using pg-pool , we are getting this errors

**Comment by charmander** [comment]
@kamarajuPrathi Which error? Are you sure it’s the same cause as this? If not, it’s best to open a new issue with full details.
