### ISSUE TITLE
How to specify the ssl certificate for connection

### ISSUE THREAD

**Issue by samehsharaf** [brianc/node-pg-pool#90]
Hi,

I need to test a new certificate for SSL connection. The idea is, I'm testing the new certificate to be used to connect to AWS Redshift based on the link: https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-transitioning-to-acm-certs.html

How can I specify the SSL certificate to be used in config when creating Pool object?

Thanks!

**Comment by brianc** [comment]
does this help? https://node-postgres.com/features/ssl
